version: "3"
services:
  qbittorrentee:
    image: superng6/qbittorrentee
    container_name: qbittorrentee
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Shanghai
    volumes:
      - /home/nasadmin/docker/qbittorrentee/config:/config
      - /home/nasadmin/docker/qbittorrentee/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    network_mode: bridge
