version: '3' 

services:
  db:
    image: mysql:latest
    container_name: nextcloud-db
    restart: unless-stopped
    # 内部暴露，不对外映射端口
    expose:
      - "3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - /home/nasadmin/docker/mysql/data:/var/lib/mysql
      - /home/nasadmin/docker/mysql/conf:/etc/mysql/conf.d


  web:
    image: nextcloud:latest
    container_name: nextcloud-web
    restart: unless-stopped
    ports:
      - "28080:80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/nasadmin/docker/nextcloud:/var/www/html
